### ISSUE TITLE
Solver meta issue

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1043]
There are a couple of solver related issues:

### Fixed by inspecting variants & variant deps

- [x] https://github.com/mamba-org/mamba/issues/658
- [x] https://github.com/mamba-org/mamba/issues/91
- [x] https://github.com/mamba-org/mamba/issues/848
- [x] https://github.com/mamba-org/mamba/issues/924

### Channel priority issues

- [x] Properly set channel priorities: https://github.com/mamba-org/mamba/issues/532
- [x] Properly do "strict" prio: https://github.com/mamba-org/mamba/issues/559
- [x] Solver sometimes stuck in a loop: #1044 
- [x] Solver is hanging #577 

### Other solver related issues

- [x] Force flag for remove: https://github.com/mamba-org/mamba/issues/412
- [x] Freeze installed solver option: https://github.com/mamba-org/mamba/issues/404
- [ ] Mamba install -c local https://github.com/mamba-org/mamba/issues/434
- [x] Respect channel pin with update https://github.com/mamba-org/mamba/issues/911
- [x] Update all not getting highest build number: https://github.com/mamba-org/mamba/issues/747
- [x] Update all dependencies: https://github.com/mamba-org/mamba/issues/52
- [x] Prune with mamba install / mamba env install https://github.com/mamba-org/mamba/issues/688
- [x] Complex update doesn't update package https://github.com/mamba-org/mamba/issues/837
- [x] Solver timeout #580

**Comment by JohanMabille** [comment]
Since there is only one remaining issue, let's close this one.
