### ISSUE TITLE
Actual "network-of-mirrors" TODO

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#648]
There are a couple of missing bits and pieces for proper network-of-mirrors:

### quetz

- [x] share download count and other stats back to main instance (PR mamba-org/quetz#266 )
- [x] mirroring without reindexing: reindexing is wasteful and CPU intensive, so maybe we can just copy from repodata.json or dump the database? (PR mamba-org/quetz#275)
- [x] implement a "known"-mirrors endpoint that the main quetz instance can return (PR mamba-org/quetz#260)

### mamba

- [ ] get fastest mirror automatically (librepo has a cool function for that)
- [ ] do not invalidate cache: need to write some "main" url into the repodata_record.json

**Comment by btel** [comment]
yep, it's done!

**Comment by JohanMabille** [comment]
Clsing this issue as mirrors have been implemented in mamba 2.
